### ISSUE TITLE
YubiHSM libusb error

### ISSUE THREAD

**Issue by naimulhq** [Yubico/python-yubihsm#23]
**Steps to Reproduce**
1. Open a terminal and start a python3 shell.
2. Write the following lines of code within the shell one at a time
```
from yubihsm.objects import AsymmetricKey
from yubihsm.defs import OBJECT
from yubihsm import YubiHsm
connector = YubiHsm.connect("http://localhost:12345")
session = connector.create_session_derived(1,"password")
AsymmetricKey.generate(session,14,"label",1,1,1)

```

**Current Behavior**

Python Shell

```
 File "<stdin>", line 1, in <module>
  File "/home/naimul/.local/lib/python3.8/site-packages/yubihsm/objects.py", line 499, in generate
    return cls._from_command(session, COMMAND.GENERATE_ASYMMETRIC_KEY, msg)
  File "/home/naimul/.local/lib/python3.8/site-packages/yubihsm/objects.py", line 186, in _from_command
    ret = session.send_secure_cmd(cmd, data)
  File "/home/naimul/.local/lib/python3.8/site-packages/yubihsm/core.py", line 372, in send_secure_cmd
    return _unpad_resp(self._secure_transceive(msg), cmd)
  File "/home/naimul/.local/lib/python3.8/site-packages/yubihsm/core.py", line 339, in _secure_transceive
    data = _unpad_resp(raw_resp, COMMAND.SESSION_MESSAGE)
  File "/home/naimul/.local/lib/python3.8/site-packages/yubihsm/core.py", line 71, in _unpad_resp
    raise YubiHsmDeviceError(six.indexbytes(resp, 3))
yubihsm.exceptions.YubiHsmDeviceError: INVALID_SESSION (error code 0x03)
```
yubihsm-connector

```
2021/12/16 14:33:37 handle_events: error: libusb: interrupted [code -10]
```

**Expected Behaviour**

The program should generate the Asymmetric Key without throwing an exception. On the software side, no overwrites were made to session to make a session invalid. My best assumption is that libusb is causing the issue. Whenever the handle_events error occurs, a session becomes valid. 

**Reported by**

Naimul

**Comment by trebortech** [comment]
I know this is an old issue but I want to help others who might get this error.

It does take a bit before it returns. ~20 seconds on my device.

My guess is your error is due to the wrong algorithms being provided.


Hope this helps


```
from yubihsm import YubiHsm
from yubihsm.objects import AsymmetricKey

hsmip = "127.0.0.1"
hsmport = 12345
authid = 1
authcode = "password"

objectid = 14
label = "My Test Key"
domains = 1
caps = 65568 # sign-pkcs and exportable-under-wrap
algo = 11  # https://developers.yubico.com/YubiHSM2/Concepts/Algorithms.html

hsm = YubiHsm.connect(f"http://{hsmip}:{hsmport}")
session = hsm.create_session_derived(authid, authcode)

AsymmetricKey.generate(session,objectid,label,domains,caps,algo)
```

**Comment by elibon99** [comment]
Closing due to inactivity. Feel free to post more info and we'll re-open it!

**Comment by iced-nero** [comment]
For what it's worth, using `yubihsm-connector 2.6.0` on a remote host `http://a.b.c.d:12345`, I tried to replicate @naimulhq issue. The first time I run `AsymmetricKey.generate(session, 14, "label", 1, 1, 1)`, I get:

```bash
Traceback (most recent call last):                                                                      
  File "<stdin>", line 1, in <module>                                                                   
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/objects.py", line 594, in generate
    return cls._from_command(session, COMMAND.GENERATE_ASYMMETRIC_KEY, msg)                             
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/objects.py", line 195, in _from_co
mmand                                                                                                   
    ret = session.send_secure_cmd(cmd, data)                                                            
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/core.py", line 747, in send_secure
_cmd                                                                                                    
    return _unpad_resp(self._secure_transceive(msg), cmd)                                               
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/core.py", line 77, in _unpad_resp 
    raise YubiHsmDeviceError(resp[3])                                                                   
yubihsm.exceptions.YubiHsmDeviceError: INVALID_DATA (error code 0x02)
```

But then after running it again I get what Naimul got before:

```bash
Traceback (most recent call last):                                                                      
  File "<stdin>", line 1, in <module>                                                                   
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/objects.py", line 594, in generate
    return cls._from_command(session, COMMAND.GENERATE_ASYMMETRIC_KEY, msg)                             
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/objects.py", line 195, in _from_co
mmand                                                                                                   
    ret = session.send_secure_cmd(cmd, data)                                                            
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/core.py", line 747, in send_secure
_cmd                                                                                                    
    return _unpad_resp(self._secure_transceive(msg), cmd)                                               
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/core.py", line 716, in _secure_tra
nsceive                                                                                                 
    data = _unpad_resp(raw_resp, COMMAND.SESSION_MESSAGE)                                               
  File ".venv/yubi/lib/python3.10/site-packages/yubihsm/core.py", line 77, in _unpad_resp 
    raise YubiHsmDeviceError(resp[3])                                                                   
yubihsm.exceptions.YubiHsmDeviceError: INVALID_SESSION (error code 0x03) 
```
