### ISSUE TITLE
Make use of `__enter__` and `__exit__`

### ISSUE THREAD

**Issue by DavidZemon** [Yubico/python-yubihsm#8]
I'm a bit bummed to see that the `yubihsm.YubiHsm` class does not implement `__enter__` and `__exit__` methods. This is a great example of a resource that should be used within a `with` clause.

```py
#!/usr/bin/python3

import yubihsm
from yubihsm.defs import CAPABILITY, ALGORITHM
from yubihsm.objects import AsymmetricKey


def main() -> None:
    print(yubihsm.__version__)
    with yubihsm.YubiHsm.connect() as hsm:
        with hsm.create_session_derived(1, 'password') as session:
            key = AsymmetricKey.generate(session, 0, "Signing key", 1, CAPABILITY.SIGN_ECDSA, ALGORITHM.EC_P256)
            data = b'Hello world!'
            signature = key.sign_ecdsa(data)
            key.delete()
            print('Signature = {}'.format(signature.decode()))


if '__main__' == __name__:
    main()
```

yields output:

```txt
2.0.1
Traceback (most recent call last):
  File "/home/david/reusable/Documents/Code/hsm-signing-server/scripts/yubihsmtest.py", line 20, in <module>
    main()
  File "/home/david/reusable/Documents/Code/hsm-signing-server/scripts/yubihsmtest.py", line 10, in main
    with yubihsm.YubiHsm.connect() as hsm:
AttributeError: __enter__
```

**Comment by DavidZemon** [comment]
Without enter/exit, I have to re-write as follows:

```py
hsm: yubihsm.YubiHsm = yubihsm.YubiHsm.connect()
try:
    session: yubihsm.core.AuthSession = hsm.create_session_derived(1, 'password')
    try:
        key = AsymmetricKey.generate(session, 0, "Signing key", 1, CAPABILITY.SIGN_ECDSA, ALGORITHM.EC_P256)
        data = b'Hello world!'
        signature = key.sign_ecdsa(data)
        key.delete()
        print('Signature = {}'.format(signature.decode()))
    finally:
        session.close()
finally:
    hsm.close()
```

**Comment by dainnilsson** [comment]
Agreed, adding enter/exit to both the connection and session makes sense.

**Comment by dquist** [comment]
How about a 2.1 release with this context manager enhancement 😊

btw this is an awesome project. Thanks for the great tooling.
